version: '3.0'
services:
  chronicle:
    image: eostribe/chronicle:latest
    volumes:
      - ./chronicle:/opt/data
    environment:
      - DATA_DIR=./data
      - MODE=scan
      - HOST=api.eostribe.io #ip address or hostname of nodeos with state-history plogin
      - PORT=8299 #port number of state history plugin
      - WS_HOST=spectrum # ip address or hostname json's consumer
      - WS_PORT=8080 # port number of json's consumer
      - SKIP_BLOCK_EVENTS=false
      - SKIP_TABLE_DELTAS=true
      - SKIP_TRACES=false
      - BIN_HEADER=false
      - EXP_WS_PATH=/
    depends_on:
      - spectrum
    links:
      - spectrum
  spectrum:
    build:
      ./spectrum
    ports:
      - 8080:8080
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_HOSTNAME=redis
  redis:
    image: redis